include:
  - project: devops/ci-config
    file:
      - /templates/audit-jobs.gitlab-ci.yml
      - /templates/container-flexible.gitlab-ci.yml
      - /templates/environments.gitlab-ci.yml
      - /templates/tag-release-version.gitlab-ci.yml
      - /templates/submodule-workflow.gitlab-ci.yml

variables:
  COMMIT_MESSAGE: "Update submodule to latest commit"
  DOWNSTREAM_PROJECT: "papyri/papyri-docker"
  DOWNSTREAM_BRANCH: "master"
  BUNDLE_GEMFILE: "Gemfile.jruby-9.4.13.0"
  RBENV_VERSION: "jruby-9.4.13.0"

stages:
  - build
  - test
  - publish
  - release
  - deploy-okd

.job:
  except:
    variables:
      - $CI_SKIP_JOB_STAGE == $CI_JOB_STAGE

build:
  extends: .build

test:
  extends: .test

release:
  extends: .release

build-cruby:
  extends: .build
  variables:
    build_tag: "$CI_REGISTRY_IMAGE/builds/cruby:$CI_COMMIT_SHORT_SHA"
    BUNDLE_GEMFILE: "Gemfile.3.2"
    RBENV_VERSION: "3.2.9"

test-cruby:
  extends: .test
  variables:
    build_tag: "$CI_REGISTRY_IMAGE/builds/cruby:$CI_COMMIT_SHORT_SHA"
    BUNDLE_GEMFILE: "Gemfile.3.2"
    RBENV_VERSION: "3.2.9"

release-cruby:
  extends: .release
  variables:
    build_tag: "$CI_REGISTRY_IMAGE/builds/cruby:$CI_COMMIT_SHORT_SHA"
    release_tag: "$CI_REGISTRY_IMAGE:cruby-$CI_COMMIT_REF_NAME"

integration-tests:
  stage: test
  extends: .trigger_downstream_pipeline
  variables:
    DOWNSTREAM_PROJECT: "papyri/papyri-docker"
    DOWNSTREAM_BRANCH: "master"
  allow_failure: true
  # Might be annoying to have this run on every commit, but it is useful to have
  when: manual

update_submodules:
  stage: publish
  extends: .update_submodule
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"

deploy-okd:
  stage: deploy-okd
  tags:
    - deploy-okd
  when: manual
  script:
    - echo "Triggering downstream deployment pipeline in dul-its/dul-papyri"
    - curl --request POST --form "token=$CI_JOB_TOKEN" --form ref=main --form "variables[BUMP_TARGET]=sosol" "https://gitlab.oit.duke.edu/api/v4/projects/dul-its%2Fdul-papyri/trigger/pipeline"