require:
  - rubocop-performance
  - rubocop-rails

Performance/ConstantRegexp:
  Enabled: false

AllCops:
  NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/ApplicationMailer:
  Enabled: false
