Rails.autoloaders.each do |autoloader|
  autoloader.inflector = Zeitwerk::Inflector.new
  autoloader.inflector.inflect(
    "jruby" => "JRuby",
    "tei" => "TEI",
    "oac" => "OAC",
    "ddb" => "DDB",
    "hgv" => "HGV",
    "dclp" => "DCLP",
    "apis" => "APIS",
    "ddb_identifier" => "DDBIdentifier",
    "ddb_identifiers_controller" => "DDBIdentifiersController",
    "hgv_identifier" => "HGVIdentifier",
    "hgv_meta_identifier" => "HGVMetaIdentifier",
    "hgv_trans_identifier" => "HGVTransIdentifier",
    "hgv_trans_identifiers_controller" => "HGVTransIdentifiersController",
    "hgv_trans_glossary" => "HGVTransGlossary",
    "hgv_trans_glossaries_controller" => "HGVTransGlossariesController",
    "hgv_meta_identifier_helper" => "HGVMetaIdentifierHelper",
    "hgv_meta_identifiers_controller" => "HGVMetaIdentifiersController",
    "dclp_meta_identifier" => "DCLPMetaIdentifier",
    "dclp_meta_identifier_helper" => "DCLPMetaIdentifierHelper",
    "dclp_meta_identifiers_controller" => "DCLPMetaIdentifiersController",
    "dclp_text_identifier" => "DCLPTextIdentifier",
    "dclp_text_identifier_helper" => "DCLPTextIdentifierHelper",
    "dclp_text_identifiers_controller" => "DCLPTextIdentifiersController",
    "apis_identifier" => "APISIdentifier",
    "apis_identifier_helper" => "APISIdentifierHelper",
    "apis_identifiers_controller" => "APISIdentifiersController",
    "oac_identifier" => "OACIdentifier",
    "oac_identifiers_controller" => "OACIdentifiersController",
    "numbers_rdf" => "NumbersRDF",
    "epidocinator" => "Epidocinator",
    "jgit" => "JGit"
  )
end
