#!/bin/sh

rm -f log/test.log
rm -f db/development.sqlite3
rm -f db/test.sqlite3
rm -rf db/test/git/boards/*
rm -rf db/test/git/users/*
rm -rf db/test/git/communities/*
rm -rf db/test/git/canonical.git
rm -rf db/git/boards/*
rm -rf db/git/users/*
rm -rf db/git/communities/*
rm -f .lock-*
echo "" > db/git/canonical.git/objects/info/alternates
bundle exec rake db:migrate:reset

