#!/usr/bin/env ruby
require 'nokogiri'
require 'open-uri'

#-------------------------------------------------------------
#  Basic configuration
#-------------------------------------------------------------
eXist = '/usr/local/exist'
canonical = '/tmp/canonical/CTS_XML_TEI/perseus'
priv = '/usr/local/texts/Work/canonical_protected/CTS_XML_TEI/perseus'
inventory = [
  '/home/ubuntu/db/repository/inventory/epifacs.xml',
  '/home/ubuntu/db/repository/inventory/annotsrc.xml',
  '/home/ubuntu/db/repository/inventory/pilots.xml',
  '/home/ubuntu/db/repository/inventory/perseus.xml']

#-------------------------------------------------------------
# Loop through the inventory files
#-------------------------------------------------------------
for file in inventory
  doc = Nokogiri::HTML(open(file))
  doc.search('online').each do |tag|
    xml = tag.attr('docname')
    path = xml.gsub( '/db/repository', '' ) # Little too specific
    #-------------------------------------------------------------
    #  There are two paths right...
    #-------------------------------------------------------------
    canonicalPath = canonical + path
    privPath = priv + path
    urn = xml.gsub( '.xml', '' )
    #-------------------------------------------------------------
    # Add the file to the eXistDB collection
    #-------------------------------------------------------------
    if File.exist?( canonicalPath )
      system eXist + '/bin/client.sh -m ' + urn + ' -p ' + canonicalPath
    elsif File.exist?( privPath )
      system eXist + '/bin/client.sh -m ' + urn + ' -p ' + privPath
    else
      puts 'Not Found:' + xml
    end
  end
end